version: '3.9'
services:
  mysqldb:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: mysqldb
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_USER: springuser
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: ecommerce_db
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    networks:
      - backend
    ports:
      - 3308:3308
    expose:
      - 3308

    volumes:
      - mysqldb:/var/lib/mysql
  app:
    image: gustavocn121/ecommerceapi
    restart: on-failure
    build: ./backend
    working_dir: /backend
    container_name: app
    environment:
      TZ: America/Sao_Paulo
      SPRING.JPA.HIBERNATE.DDL-AUTO: update
      SPRING.DATASOURCE.URL: jdbc:mysql://mysqldb:3308/ecommerce_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING.DATASOURCE.USERNAME: springuser
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.DATASOURCE.DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING.JPA.DATABASE-PLATAFORM: org.hibernate.dialect.MySQL5InnoDBDialect
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - mysqldb
    networks:
        - backend
        - frontend
networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge
volumes:
  mysqldb: